# Generated by Django 3.0.7 on 2020-06-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Free', 'FREE'), ('Q1', 'Quote_One'), ('Q2', 'Quote Two'), ('Q3', 'Qutoe Three')], default='Free', max_length=54),
        ),
    ]
