# Generated by Django 3.0.7 on 2020-06-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200614_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
