# Generated by Django 3.0 on 2020-08-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user_membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UserMembership',
        ),
    ]
