# Generated by Django 3.0 on 2020-08-14 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0022_assignment_support'),
        ('payments', '0008_order_support'),
        ('chat', '0002_thread_third'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.Assignment'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='notification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Order'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='viewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
