# Generated by Django 3.0.7 on 2020-06-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200607_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_administrator',
            field=models.BooleanField(default=False, verbose_name=' Check the checkbox alongside to signup as an Administrator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name=' Check the checkbox alongside to signup as Client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(default=False, verbose_name=' Check the checkbox alongside to signup as Writer'),
        ),
    ]
