# Generated by Django 3.0.8 on 2020-08-06 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20200730_0631'),
        ('authentication', '0008_notification_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Order'),
        ),
    ]
