# Generated by Django 3.0.6 on 2020-06-02 12:45

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('one', 'level_one'), ('two', 'level_two')], max_length=20)),
                ('types', models.CharField(choices=[('one', 'type_one'), ('two', 'type_two')], max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
