# Generated by Django 3.0.6 on 2020-06-02 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignmentdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assignments',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 2, 13, 32, 30, 806310, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
