# Generated by Django 3.0.6 on 2020-06-02 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20200602_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 13, 52, 48, 609896, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignments',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='course_description'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='level',
            field=models.CharField(choices=[('HS', 'High School'), ('CO', 'College'), ('UN', 'University'), ('MS', 'Masters'), ('PHD', 'Ph.D')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='types',
            field=models.CharField(choices=[('DN', 'Discussion'), ('QZ', 'QUIZ'), ('OC', 'Online Course'), ('EX', 'Exam'), ('HW', 'Homework'), ('ESS', 'Essay'), ('RP', 'Research Paper'), ('SA', 'Statistical Analysis'), ('PRO', 'Project'), ('DI', 'Dissertation'), ('PRE', 'Presentation'), ('O', 'Others')], max_length=20),
        ),
    ]
