# Generated by Django 3.0.7 on 2020-06-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20200602_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='is_approved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
