# Generated by Django 3.0.7 on 2020-06-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignments_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignments',
            name='revise',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
