# Generated by Django 3.0.7 on 2020-06-13 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0006_auto_20200604_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='AssignmentDocuments',
        ),
        migrations.AddField(
            model_name='assignments',
            name='allowed_memberships',
            field=models.ManyToManyField(null=True, to='payments.Membership'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='assignments',
            field=models.ManyToManyField(to='assignments.Assignments'),
        ),
        migrations.AddField(
            model_name='writer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writers', to=settings.AUTH_USER_MODEL),
        ),
    ]
