# Generated by Django 3.0.7 on 2020-06-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('assignments', '0008_auto_20200613_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='allowed_memberships',
            field=models.ManyToManyField(to='payments.Membership'),
        ),
    ]
