# Generated by Django 3.0.7 on 2020-06-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_assignments_more_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='more_info',
            field=models.TextField(max_length=1200, null=True, verbose_name='More Information Section'),
        ),
    ]
