# Generated by Django 3.0.7 on 2020-06-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_auto_20200622_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='solution_format',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
