# Generated by Django 3.0.7 on 2020-07-23 16:51

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('payments', '0004_membership_payment_status'),
        ('assignments', '0013_assignments_solution_format'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignments',
            new_name='Assignment',
        ),
    ]
