# Generated by Django 3.0.8 on 2020-07-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_auto_20200729_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
