# Generated by Django 3.0.8 on 2020-07-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0016_assignment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(blank=True, choices=[('APP', 'Approved'), ('PEN', 'Pending'), ('COMP', 'Completed')], max_length=23, null=True),
        ),
    ]
