# Generated by Django 3.0.8 on 2020-07-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0018_auto_20200730_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='allowed_memberships',
        ),
    ]
