# Generated by Django 3.0.8 on 2020-08-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0020_assignment_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='return_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
