# Generated by Django 3.0 on 2020-08-14 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200814_0340'),
        ('assignments', '0022_assignment_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Thread'),
        ),
    ]
