# Generated by Django 3.0 on 2020-08-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0023_assignment_thread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(blank=True, choices=[('APP', 'Approved'), ('PEN', 'Ongoing'), ('COMP', 'Completed'), ('REV', 'Return for Revision'), ('BID', 'Not Yet Bidded'), ('PRIV', 'Private')], default='PRIV', max_length=23, null=True),
        ),
    ]
