# Generated by Django 3.0 on 2020-08-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0025_auto_20200816_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='thread',
        ),
    ]
