# Generated by Django 3.0 on 2020-09-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0027_auto_20200824_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
