# Generated by Django 3.0 on 2020-09-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0028_assignment_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='task',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='writer_document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
