# Generated by Django 3.0 on 2020-09-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0030_assignment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='writers_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
