# Generated by Django 3.0 on 2020-09-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0032_auto_20200902_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='price_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
