# Generated by Django 3.0 on 2020-09-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0033_assignment_price_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='writers_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
