# Generated by Django 3.0 on 2020-09-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0034_assignment_writers_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='assignment',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(blank=True, choices=[('APP', 'Approved'), ('PEN', 'Ongoing'), ('COMP', 'Completed'), ('REV', 'Return for Revision'), ('BID', 'Accept'), ('PRIV', 'Private'), ('DIS', 'Disputed'), ('MP', 'Mark Paid')], default='PRIV', max_length=23, null=True),
        ),
    ]
